### ISSUE TITLE
When I upload video, I encounter an issue, kindly help me with this

### ISSUE THREAD

**Issue by JohnnyFire** [experience-ml/cartoonize#11]
Hi Professor,

Could you please help me with this?
Reproduce step: install it on windows, when cartoonize the video, there is an error as follow;

Best regards,

'D:\Workspace\cartoonize\static\uploaded_videos\22a98314-0571-4b48-93b3-def5f768314a_modified.mp4': Invalid argument
Traceback (most recent call last):
  File "app.py", line 149, in cartoonize
    cartoon_video_path = wb_cartoonizer.process_video(modified_video_path, output_frame_rate)
  File "./white_box_cartoonizer\cartoonize.py", line 113, in process_video
    out.close()
  File "D:\ProgramData\Anaconda3\lib\site-packages\skvideo\io\abstract.py", line 474, in close
    if self._proc is None:  # pragma: no cover
AttributeError: 'FFmpegWriter' object has no attribute '_proc'
None
[2021-02-10 23:48:13,763] ERROR in app: Exception on /cartoonize [POST]
Traceback (most recent call last):
  File "app.py", line 149, in cartoonize
    cartoon_video_path = wb_cartoonizer.process_video(modified_video_path, output_frame_rate)
  File "./white_box_cartoonizer\cartoonize.py", line 113, in process_video
    out.close()
  File "D:\ProgramData\Anaconda3\lib\site-packages\skvideo\io\abstract.py", line 474, in close
    if self._proc is None:  # pragma: no cover
AttributeError: 'FFmpegWriter' object has no attribute '_proc'

**Comment by JohnnyFire** [comment]
It is the same issue with the issue previous created
