### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by Jo-Hyman** [experience-ml/cartoonize#12]
i run this project at docker. the env is ubuntu18.04. but error. please 
-----------------
[2021-03-01 03:01:03 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-03-01 03:01:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-03-01 03:01:03 +0000] [1] [INFO] Using worker: threads
[2021-03-01 03:01:03 +0000] [9] [INFO] Booting worker with pid: 9
2021-03-01 03:01:04.082719: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-03-01 03:01:04.082791: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-03-01 03:01:04.082804: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[2021-03-01 03:01:04 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/app.py", line 44, in <module>
    wb_cartoonizer = WB_Cartoonize(os.path.abspath("white_box_cartoonizer/saved_models/"), opts['gpu'])
  File "./white_box_cartoonizer/cartoonize.py", line 27, in __init__
    self.load_model(weights_dir, gpu)
  File "./white_box_cartoonizer/cartoonize.py", line 54, in load_model
    self.final_out = guided_filter.guided_filter(self.input_photo, network_out, r=1, eps=5e-3)
  File "./white_box_cartoonizer/guided_filter.py", line 30, in guided_filter
    N = tf_box_filter(tf.ones((1, x_shape[1], x_shape[2], 1), dtype=x.dtype), r)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2659, in ones
    output = _constant_if_small(one, shape, dtype, name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2391, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 728, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array.
[2021-03-01 03:01:04 +0000] [9] [INFO] Worker exiting (pid: 9)
[2021-03-01 03:01:05 +0000] [1] [INFO] Shutting down: Master
[2021-03-01 03:01:05 +0000] [1] [INFO] Reason: Worker failed to boot.
-----------

**Comment by Badb100d** [comment]
> ## i run this project at docker. the env is ubuntu18.04. but error. please
> ## [2021-03-01 03:01:03 +0000] [1] [INFO] Starting gunicorn 20.0.4
> [2021-03-01 03:01:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
> [2021-03-01 03:01:03 +0000] [1] [INFO] Using worker: threads
> [2021-03-01 03:01:03 +0000] [9] [INFO] Booting worker with pid: 9
> 2021-03-01 03:01:04.082719: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
> 2021-03-01 03:01:04.082791: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
> 2021-03-01 03:01:04.082804: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use `layer.__call__` method instead.
> WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.**init** (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> [2021-03-01 03:01:04 +0000] [9] [ERROR] Exception in worker process
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
> worker.init_process()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
> super().init_process()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
> self.load_wsgi()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
> self.wsgi = self.app.wsgi()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
> self.callable = self.load()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
> return self.load_wsgiapp()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
> return util.import_app(self.app_uri)
> File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
> mod = importlib.import_module(module)
> File "/usr/local/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/app/app.py", line 44, in
> wb_cartoonizer = WB_Cartoonize(os.path.abspath("white_box_cartoonizer/saved_models/"), opts['gpu'])
> File "./white_box_cartoonizer/cartoonize.py", line 27, in **init**
> self.load_model(weights_dir, gpu)
> File "./white_box_cartoonizer/cartoonize.py", line 54, in load_model
> self.final_out = guided_filter.guided_filter(self.input_photo, network_out, r=1, eps=5e-3)
> File "./white_box_cartoonizer/guided_filter.py", line 30, in guided_filter
> N = tf_box_filter(tf.ones((1, x_shape[1], x_shape[2], 1), dtype=x.dtype), r)
> File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2659, in ones
> output = _constant_if_small(one, shape, dtype, name)
> File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2391, in _constant_if_small
> if np.prod(shape) < 1000:
> File "<**array_function** internals>", line 6, in prod
> File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
> keepdims=keepdims, initial=initial, where=where)
> File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
> return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 728, in **array**
> " array.".format(self.name))
> NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array.
> [2021-03-01 03:01:04 +0000] [9] [INFO] Worker exiting (pid: 9)
> [2021-03-01 03:01:05 +0000] [1] [INFO] Shutting down: Master
> [2021-03-01 03:01:05 +0000] [1] [INFO] Reason: Worker failed to boot.

Add **"numpy==1.19"** to the first line of requirements.txt solved the problem, looks like newer numpy has some newer features.

**Comment by Badb100d** [comment]
Add **`numpy==1.19`** to the first line of requirements.txt solved the problem, looks like newer numpy has some newer features.

**Comment by nirajpandkar** [comment]
Thank you @Badb100d for the solution. @Jo-Hyman can you check whether that solves the problem for you? Sorry for the late reply!

**Comment by avukonkepeter** [comment]
@Badb100d Your solution worked for me +1

**Comment by MorningStarJ** [comment]
@nirajpandkar Thank you for your great work. I have a similarly error,after add numpy==1.19 to the first line of requirements.txt docker can start a container, just without using GPU. Maybe I need use `docker pull tensorflow/tensorflow:2.1.0-gpu-py3` and base on `tensorflow/tensorflow:2.1.0-gpu-py3` to re-build a image?
```
2021-09-16 12:38:22.808434: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-09-16 12:38:22.808496: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-09-16 12:38:22.808503: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2021-09-16 12:38:23.453943: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-16 12:38:23.474577: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3699850000 Hz
2021-09-16 12:38:23.474938: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5581e782cf00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-16 12:38:23.474951: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-09-16 12:38:23.476195: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-09-16 12:38:23.584028: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-16 12:38:23.584396: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5581e77fd1f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-09-16 12:38:23.584411: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1080 Ti, Compute Capability 6.1
2021-09-16 12:38:23.584528: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-16 12:38:23.584801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.607GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-09-16 12:38:23.584891: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.584945: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.584992: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.585038: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.585084: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.585131: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.585177: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2021-09-16 12:38:23.585184: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

**Comment by nirajpandkar** [comment]
@MorningStarJ Glad you got the issue resolved!

I'm closing this issue since @Badb100d solutions seems to work for others as well. @Jo-Hyman Let me know if it the problem still persists.
