### ISSUE TITLE
error - cannot import markup from jinja2

### ISSUE THREAD

**Issue by nonvegetarian** [experience-ml/cartoonize#32]
[2023-10-10 12:43:22 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2023-10-10 12:43:22 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2023-10-10 12:43:22 +0000] [1] [INFO] Using worker: threads
[2023-10-10 12:43:22 +0000] [9] [INFO] Booting worker with pid: 9
[2023-10-10 12:43:24 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/app.py", line 13, in <module>
    from flask import Flask, render_template, make_response, flash
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)
[2023-10-10 12:43:24 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-10-10 12:43:24 +0000] [1] [INFO] Shutting down: Master
[2023-10-10 12:43:24 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by dan-r95** [comment]
Use fork
https://github.com/yalay/cartoonize

**Comment by tek-life** [comment]
> Use fork https://github.com/yalay/cartoonize

Step 6/13 : RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list
 ---> Running in 776f26d38f6b
sed: can't read /etc/apt/sources.list: No such file or directory
The command '/bin/sh -c sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list' returned a non-zero code: 2
