### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by shivsah** [experience-ml/cartoonize#9]
```
The system cannot find the path specified.
'F:\PongGame\Test\cartoonize\static\uploaded_videos\e0db715a-a588-4442-900a-c4145bcc56ee.mp4': Invalid argument
The system cannot find the path specified.
'F:\PongGame\Test\cartoonize\static\uploaded_videos\e0db715a-a588-4442-900a-c4145bcc56ee_modified.mp4': Invalid argument
Traceback (most recent call last):
  File "F:\PongGame\Test\cartoonize\app.py", line 149, in cartoonize
    cartoon_video_path = wb_cartoonizer.process_video(modified_video_path, output_frame_rate)
  File "./white_box_cartoonizer\cartoonize.py", line 113, in process_video
    out.close()
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python37\lib\site-packages\skvideo\io\abstract.py", line 474, in close
    if self._proc is None:  # pragma: no cover
AttributeError: 'FFmpegWriter' object has no attribute '_proc'
None
127.0.0.1 - - [17/Jan/2021 01:12:57] "POST /cartoonize HTTP/1.1" 200 -
The system cannot find the path specified.
'F:\PongGame\Test\cartoonize\static\uploaded_videos\1ae5112d-a042-4366-8f06-b5d954955c61.mp4': Invalid argument
The system cannot find the path specified.
'F:\PongGame\Test\cartoonize\static\uploaded_videos\1ae5112d-a042-4366-8f06-b5d954955c61_modified.mp4': Invalid argument
Traceback (most recent call last):
  File "F:\PongGame\Test\cartoonize\app.py", line 149, in cartoonize
    cartoon_video_path = wb_cartoonizer.process_video(modified_video_path, output_frame_rate)
  File "./white_box_cartoonizer\cartoonize.py", line 113, in process_video
    out.close()
```

This seem to only happen with video files, whereas the images are working fine.

OS :- Windows 10
Python Version :- 3.7
GPU Enabled :- Yes
Debug :- True

**Comment by nirajpandkar** [comment]
I'm not in front of a system but from my previous experience, if it can't find the folder means you'll have to create the specified folders in "static" folder. If I recall correctly, there are 2 which are required out of which one is "uploaded_videos". 

Let me know if it doesn't fix the issue :)

**Comment by shivsah** [comment]
![image](https://user-images.githubusercontent.com/17703895/104821739-f330cb80-5863-11eb-883e-ba2efccf7f02.png)
They already exist..I even checked the files. so the upload is working properly.

Looks like I'll have to move into Ubuntu machine now..

Windows is a no-go

**Comment by JohnnyFire** [comment]
I GOT THE SAME ISSUE.
'D:\Workspace\cartoonize\static\uploaded_videos\4cf7c7ed-1485-48d4-bc0e-ee181337b728.mp4': Invalid argument
'D:\Workspace\cartoonize\static\uploaded_videos\4cf7c7ed-1485-48d4-bc0e-ee181337b728_modified.mp4': Invalid argument
Traceback (most recent call last):
  File ".\app.py", line 149, in cartoonize
    cartoon_video_path = wb_cartoonizer.process_video(modified_video_path, output_frame_rate)
  File "./white_box_cartoonizer\cartoonize.py", line 113, in process_video
    out.close()
  File "D:\ProgramData\Anaconda3\lib\site-packages\skvideo\io\abstract.py", line 474, in close
    if self._proc is None:  # pragma: no cover
AttributeError: 'FFmpegWriter' object has no attribute '_proc'
[2021-02-10 23:01:28,080] ERROR in app: Exception on /cartoonize [POST]
Traceback (most recent call last):
  File ".\app.py", line 149, in cartoonize
    cartoon_video_path = wb_cartoonizer.process_video(modified_video_path, output_frame_rate)
  File "./white_box_cartoonizer\cartoonize.py", line 113, in process_video
    out.close()
  File "D:\ProgramData\Anaconda3\lib\site-packages\skvideo\io\abstract.py", line 474, in close
    if self._proc is None:  # pragma: no cover
AttributeError: 'FFmpegWriter' object has no attribute '_proc'

**Comment by shivsah** [comment]
You should use a linux system or WSL..

**Comment by JohnnyFire** [comment]
@shivsah Could you please tell me the steps of using WSL, should I move my code to WSL and install cuda again using WSL? Plus, my host os is windows10 enterprise with GTX 1070, does WSL support GPU virtualization? Appreciated :)

**Comment by tjdevWorks** [comment]
Due to no activity, I am closing this issue.
